mvw/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mvw.accounts.views import signup, update_user, delete_user, activate, forgotten_password, password_change, \
    sign_in, sign_out, list_users, create_user

app_name = 'accounts'

urlpatterns = [
    path('login/', sign_in, name='login'),
    path('logout/', sign_out, name='logout'),
    path('signup/', signup, name='signup'),
    path('activate/<str:username>/<str:token>', activate, name='activate'),
    path('profile/', update_user, name='profile'),

    path('users', list_users, name='list_users'),
    path('create/', create_user, name='create_user'),
    path('update/', update_user, name='update_user'),
    path('delete/', delete_user, name='delete_user'),

    path('forgotten/', forgotten_password, name='forgotten'),
    path('forgotten/done/', TemplateView.as_view(template_name='forgotten_password_done.html'),
         name='forgotten_password_done'),
    path('password_change/<int:user_id>/', password_change, name='password_change'),
]

"""
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

mvw/core/urls.py
from django.urls import path
from .views import index

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
]

mvw/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mvw.core.urls")),
    path("walk/", include("mvw.walk.urls")),
    path("accounts/", include("mvw.accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

mvw/walk/urls.py
from django.urls import path
from .views import home, dashboard, walk_chart, add_walk

app_name = "walk"

urlpatterns = [
    path("", home, name="home"),
    path('walk-chart/', walk_chart, name='walk-chart'),
    path("dashboard", dashboard, name="dashboard"),
    path("add-walk", add_walk, name="add-walk"),
]

mvw/core/models.py
from django.db import models

# Create your models here.

mvw/core/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)

mvw/core/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def index(request):
    return render(request, 'core/index.html', {'user': request.user, })

mvw/core/templates/core/includes/footer.html
<div class="navbar footer">
  <div class="container">
      <div class="col-md-6 legal">
        <span>© 2020-2025 Marques Ltd.</span>
      </div>
      <div class="col-md-6 social">
        <a href="https://github.com/pepcmarques/circularis" target="_blank" data-toggle="tooltip" title="Github" data-placement="top">
          <span class="fab fa-github"></span>
        </a>
        <a href="https://twitter.com/pepcmarques" target="_blank" data-toggle="tooltip" title="Twitter" data-placement="top">
          <span class="fab fa-twitter"></span>
        </a>
        <a href="https://youtube.com/pepcmarques/" target="_blank" data-toggle="tooltip" title="Youtube" data-placement="top">
          <span class="fab fa-youtube"></span>
        </a>
        <a href="https://plus.google.com/+pepcmarques/" target="_blank" data-toggle="tooltip" title="Google+" data-placement="top">
          <span class="fab fa-google-plus"></span>
        </a>
      </div>
  </div>
</div>

mvw/core/templates/core/includes/header.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container">
      <a href="{% url 'walk:home' %}" class="navbar-brand value-brand">Marpole Virtual Walk</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              {% if user.is_authenticated %}
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'walk:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'walk:dashboard' %}">Dashboard</span></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'walk:add-walk' %}">Add Walk</span></a>
                  </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <span class="navbar-text username-divider"></span>
                </li>
                <li>
                  <span class="navbar-text">Hi {{ request.user.username }}</span>
                </li>
                <span class="navbar-text username-divider"></span>
                <li>
                    <a href="{% url 'accounts:profile' %}"><span class="navbar-text"><i class="fa fa-cog" style="margin-top:5px;"></i></span></a>
                </li>
                <span class="navbar-text username-divider"></span>
                <li>
                  <a href="{% url 'logout' %}">
                      <div style="margin-top: 5px;">
                        <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="Sign out">
                          <span class="navbar-text"><i class="fas fa-sign-out-alt"></i></span>
                        </span>
                      </div>
                  </a>
                </li>
              </ul>
            {% else %}
              <ul class="navbar-nav mr-auto">
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li class="nav-item">
                      <a href="{% url 'accounts:login' %}" class="nav-link">Sign in</a>
                  </li>
                  <li>
                    <span class="navbar-text username-divider"></span>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'accounts:signup' %}" class="nav-link">Sign up</a>
                  </li>
              </ul>
            {% endif %}
          </div>
    </div>
  </nav>
</header>

mvw/core/templates/core/includes/messages.html
{% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}