mvw/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mvw.core.urls")),
    path("walk/", include("mvw.walk.urls")),
    path("accounts/", include("mvw.accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

mvw/walk/urls.py
from django.urls import path
from .views import home, dashboard, walk_chart, add_walk

app_name = "walk"

urlpatterns = [
    path("", home, name="home"),
    path('walk-chart/', walk_chart, name='walk-chart'),
    path("dashboard", dashboard, name="dashboard"),
    path("add-walk", add_walk, name="add-walk"),
]

mvw/walk/models.py
from django.db import models
from django.contrib.auth.models import User


class Walk(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    walkDate = models.DateField()
    distance = models.IntegerField()
    minutes = models.IntegerField()

    def __str__(self):
        return f"{self.user} - {self.walkDate} - {self.distance}Km - {self.minutes}min."


class VisitingPoint(models.Model):
    name = models.CharField(max_length=50)
    order_no = models.IntegerField()
    km = models.IntegerField()
    picture_name = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


"""
William Mackie Park - 01_wmp.png
"""

mvw/walk/forms.py
from django.forms import ModelForm
from django import forms

from .models import Walk

DISTANCE_CHOICES = list(range(1, 11))
MINUTE_CHOICES = list(range(1, 121))


class DateInput(forms.DateInput):
    input_type = 'date'


class WalkForm(ModelForm):
    class Meta:
        model = Walk
        fields = ["walkDate", "distance", "minutes"]
        labels = {
            'walkDate': 'Date or your walk',
            'distance': 'Rounded distance (Km)',
            'minutes': 'Walk duration (minutes)',
        }
        widgets = {
            "walkDate": DateInput(),
            "distance": forms.Select(choices=list(zip(DISTANCE_CHOICES, DISTANCE_CHOICES)), attrs={'class': 'form-control'}),
            "minutes": forms.Select(choices=list(zip(MINUTE_CHOICES, MINUTE_CHOICES)), attrs={'class': 'form-control'})
        }

mvw/walk/views.py
import pandas as pd

from django.contrib.auth.decorators import login_required
from django.db.models import Func, Sum
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import JsonResponse

from .forms import WalkForm
from .models import Walk, VisitingPoint


def get_walks(request):
    user = request.user
    walks = Walk.objects.filter(user=user)
    return walks


def walk_chart(request):
    walks = get_walks(request)
    labels, data = walk_bar_chart(walks)

    return JsonResponse(data={
        "labels": labels,
        "data": data,
    })


def walk_bar_chart(walks):
    df = pd.DataFrame.from_records(walks.values())

    if df.shape == (0, 0):
        return None, None

    labels = [d for d in df["walkDate"]]
    data = [d for d in df["distance"]]

    return labels, data


def get_goal_and_points():
    points = VisitingPoint.objects.all().order_by('order_no').values()
    """
    points = (
        VisitingPoint.objects.annotate(
            cumsum=Func(
                Sum('km'),
                template='%(expressions)s OVER (ORDER BY %(order_by)s)',
                order_by="id"
            )
        ).values('order_no', 'picture_name', 'name', 'km', 'description', 'cumsum').order_by('order_no', 'cumsum')
    )
    goal = sum([p["km"] for p in points])
    """
    goal = len(points)
    return goal, points


@login_required()
def home(request):
    walks = get_walks(request)
    goal, points = get_goal_and_points()
    return render(request, "walk/index.html", {"walks": walks, "walked_number": len(walks), "goal_distance": goal,
                                               "points": points})


@login_required()
def dashboard(request):
    walks = get_walks(request)
    chart_labels, chart_data = walk_bar_chart(walks)
    return render(request,
                  "walk/dashboard.html",
                  {"walks": walks, "chart_labels": chart_labels, "chart_data": chart_data}
                  )


@login_required()
def add_walk(request):
    if request.method == 'POST':
        form = WalkForm(request.POST)
        if form.is_valid():
            new_walk = form.save(commit=False)
            new_walk.user = request.user
            new_walk.save()
            return redirect(reverse('walk:home'))
    else:
        form = WalkForm()
    return render(request, 'walk/add_walk.html', {'form': form})

mvw/walk/templates/walk/add_walk.html
{% extends 'core/base.html'%}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Walk</h1>
    <form action="{% url 'walk:add-walk' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-success">
    </form>

{% endblock content %}

mvw/walk/templates/walk/dashboard.html
<!-- templates/dashboard.html -->
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

{% if walks %}
    <div>
        <div>
            <table class="table">
                <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time (minutes)</th>
                    <th scope="col">Distance (Km)</th>
                </tr>
                </thead>
                <tbody>
                {% for walk in walks %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{walk.walkDate}}</td>
                    <td>{{walk.minutes}}</td>
                    <td>{{walk.distance}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            <canvas id="walk-chart" data-url="{% url 'walk:walk-chart' %}"></canvas>
        </div>
    </div>
    {% else %}
    <div>
        <h3>You did not registered any walk...</h3>
        <h3>Kindly, click on "Add Walk" on the menu, and add the information about your walk.</h3>
    </div>
    {% endif %}

{% endblock content %}

{% block javascript %}

<script>
    $(function () {

      var $walkChart = $("#walk-chart");
      $.ajax({
        url: $walkChart.data("url"),
        success: function (data) {

          var ctx = $walkChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'walk',
                backgroundColor: '#327838',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Walk Bar Chart'
              },
              scales: {
                  yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: .5
                    }
                  }]
              }
            }
          });

        }
      });

    });
</script>

{% endblock javascript %}

mvw/walk/templates/walk/index.html
<!-- templates/dashboard.html -->
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}

{% load static %}
{% load custom_filters %}

{% block content %}

{% if walked_number == 0 %}
<div>
    <h3>You did not register any walk. Please add a walk to see your progress.</h3>
</div>
{% else %}
<div>
    <div>
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0px" y="0px" viewBox="0 0 200 60">
            <path fill-opacity="0" stroke-width="2" stroke="#bbb" d="M10,10h180v10h-180v10h180v10h-180v10h180"/>
            <path id="walk-path" fill-opacity="0" stroke-width="3" stroke="#327838" d="M10,10h180v10h-180v10h180v10h-180v10h180"/>
        </svg>
    </div>
    <div>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th style="width: 10%" scope="col">#</th>
                <th style="width: 10%" scope="col">Image</th>
                <th style="width: 30%" scope="col">Name</th>
                <th style="width: 50%" scope="col">Description</th>
            </tr>
            </thead>
            <tbody>
            {% for point in points %}
                {% with next_element=points|next:forloop.counter0 %}
                {% if walked_number >= forloop.counter %}
                <tr>
                    <td style="vertical-align: middle;" scope="row">{{forloop.counter}}</td>
                    <td  style="vertical-align: middle;" ><img src="{% static 'img/points/' %}{{ point.picture_name }}" width="150px" /></td>
                    <td style="vertical-align: middle;">{{point.name}}</td>
                    <td style="vertical-align: middle;">
                        {{point.description}}.<br />
                        {% if next_element %}
                            Next stop is <b>{{next_element.name}}</b>.
                        {% else %}
                            This is your last stop! Thank you for participating on Marpole Virtual Walk.
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}

{% endblock content %}

{% block javascript %}

{{ walked_number|json_script:"walked" }}
{{ goal_distance|json_script:"goal" }}

<script>
var bar = new ProgressBar.Path('#walk-path', {
    easing: 'easeInOut',
    duration: 1400
});

const walked_number = JSON.parse(document.getElementById('walked').textContent);
const total = JSON.parse(document.getElementById('goal').textContent);;

var percent = (walked_number * 1) / total

if (percent > 1) {
    percent = 1;
}

bar.set(0);
bar.animate(percent);  // Number from 0.0 to 1.0
</script>

{% endblock javascript %}