mvw/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mvw.accounts.views import signup, update_user, delete_user, activate, forgotten_password, password_change, \
    sign_in, sign_out, list_users, create_user

app_name = 'accounts'

urlpatterns = [
    path('login/', sign_in, name='login'),
    path('logout/', sign_out, name='logout'),
    path('signup/', signup, name='signup'),
    path('activate/<str:username>/<str:token>', activate, name='activate'),
    path('profile/', update_user, name='profile'),

    path('users', list_users, name='list_users'),
    path('create/', create_user, name='create_user'),
    path('update/', update_user, name='update_user'),
    path('delete/', delete_user, name='delete_user'),

    path('forgotten/', forgotten_password, name='forgotten'),
    path('forgotten/done/', TemplateView.as_view(template_name='forgotten_password_done.html'),
         name='forgotten_password_done'),
    path('password_change/<int:user_id>/', password_change, name='password_change'),
]

"""
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

mvw/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mvw.core.urls")),
    path("walk/", include("mvw.walk.urls")),
    path("accounts/", include("mvw.accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

mvw/walk/urls.py
from django.urls import path
from .views import home, dashboard, walk_chart, add_walk

app_name = "walk"

urlpatterns = [
    path("", home, name="home"),
    path('walk-chart/', walk_chart, name='walk-chart'),
    path("dashboard", dashboard, name="dashboard"),
    path("add-walk", add_walk, name="add-walk"),
]

mvw/accounts/models.py
from django.db import models

# Create your models here.

mvw/accounts/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, help_text='username required')
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=50, help_text='username required')
    email = forms.EmailField(max_length=200, help_text='email required')

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already registered")
        return email


class ForgottenPasswordForm(forms.Form):
    email = forms.EmailField(
        label=gettext_lazy('Email'),
        widget=forms.TextInput(attrs={'class': 'span3'}))


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UsersForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        labels = {'username': 'Username', 'email': 'e-mail'}


class UsersUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username': 'Username',
            'first_name': 'First name',
            'last_name': 'Last name',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True
        self.fields['email'].disabled = True


class PasswordChangeForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].disabled = True

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(PasswordChangeForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

mvw/accounts/views.py
# accounts/views.py
from django.contrib import auth, messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.shortcuts import redirect, render
from django.utils.http import url_has_allowed_host_and_scheme, urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse

from django.contrib.auth.models import User

from mvw.settings import SYSTEM_NAME

from mvw.accounts.forms import LoginForm, UsersForm, UsersUpdateForm, SignupForm, ForgottenPasswordForm, \
    PasswordChangeForm
from mvw.accounts.tokens import account_activation_token

import base64
import qrcode
import io


def make_code(url):
    image = qrcode.make(url)
    return image


def get_redirect_path(request):
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    if url_has_allowed_host_and_scheme(redirect_path, request.get_host()):
        return redirect_path
    else:
        return "/walk/"


def sign_in(request):
    if request.user.is_authenticated:
        return redirect('/')

    form = LoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            # correct username and password login the user
            auth.login(request, user)
            print(get_redirect_path(request))
            return redirect(get_redirect_path(request))
        else:
            return redirect('/')

    return render(request, 'accounts/login.html', {'form': form})


def sign_out(request):
    auth.logout(request)
    return redirect('/')


#def logout_view(request):
#    logout(request)
#    return redirect('/')


def build_message(request, template, user):
    current_site = get_current_site(request)
    message = render_to_string(template, {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
    })
    return message


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            from .tokens import account_activation_token as token

            new_user = form.save(commit=False)
            new_user.is_active = False
            new_user.save()
            # https://stackoverflow.com/questions/76580910/is-it-possible-to-create-a-qr-code-for-an-image-using-the-python-qrcode-library
            domain = request.META['HTTP_HOST']
            username = new_user.username
            url = f"http://{domain}/accounts/activate/{username}/{token.make_token(new_user)}"
            qr = make_code(url)
            #
            temp = io.BytesIO()
            qr.save(temp)
            temp.seek(0)
            b = temp.read()
            b64 = 'data:image/gif;base64,' + base64.standard_b64encode(b).decode()
            #
            return render(request, 'accounts/complete.html', {"qr64": b64, "url_complete": url})
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def activate(request, username, token):
    try:
        username = force_str(username)
        user = User.objects.get(username=username)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        print("here")
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request,  'core/index.html',
                      {'message': "Thank you for clicking on the link. Now you can start using the system."})
    else:
        return render(request, 'core/index.html', {'message': 'Activation link is invalid!'})


@sensitive_post_parameters()
@csrf_protect
@never_cache
def forgotten_password(request):
    if request.method == 'POST':
        form = ForgottenPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email=form.cleaned_data['email'])
            if user:
                user = user[0]  # first and only user
                #
                mail_subject = 'Password reset for your {0} account.'.format(SYSTEM_NAME)
                message = build_message(request, "accounts/acc_reset_password.html", user)
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                #
            return redirect('accounts:forgotten_password_done')
    else:
        form = ForgottenPasswordForm()
    return render(request, 'accounts/forgotten.html', {'form': form})


def profile(request, user_id):
    return update_user(request, user_id)


@user_passes_test(lambda u: u.is_superuser)
def list_users(request):
    users = User.objects.order_by('email')
    return render(request, 'accounts/users.html', {'users': users})


@user_passes_test(lambda u: u.is_superuser)
def create_user(request):
    form = UsersForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('list_users')
    return render(request, 'accounts/user-form.html', {'form': form})


@login_required()
def update_user(request):
    user = request.user
    form = UsersUpdateForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect(reverse('walk:home'))
    return render(request, 'accounts/user-form.html', {'form': form, 'user': user})


def password_change(request, user_id):
    if not request.user.is_superuser:
        if request.user.id != user_id:
            return redirect(reverse('base:index'))
    user = User.objects.get(id=user_id)
    form = PasswordChangeForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        login(request, user)
        return render(request,  'core/index.html', {'message': "Password was set!"})
    return render(request, 'accounts/password_change.html', {'form': form, 'user': user})


# @user_passes_test(lambda u: u.is_superuser)
def delete_user(request):
    user = request.user
    if request.method == 'POST':
        user.delete()
        auth.logout(request)
        return redirect(reverse('core:index'))
    return render(request, 'accounts/user-delete-confirm.html', {'user': user})

mvw/accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hello,

You are receiving this email because we got an account creation request for {{ user.email }}.

Please click on the link to confirm your registration,

http://{{ domain }}{% url 'accounts:activate' uid token %}

Kindly ignore this email if you did not request the account creation.

{% endautoescape %}

mvw/accounts/templates/accounts/acc_reset_password.html
{% autoescape off %}
Hello,

You are receiving this email because we got a reset password request for {{ user.email }}.

Please click on the link to reset your password,

http://{{ domain }}{% url 'accounts:activate' uid token %}

Kindly ignore this email if you did not request to reset your password.

{% endautoescape %}

mvw/accounts/templates/accounts/complete.html
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

<div>
	<h3>Please confirm your registration by scanning this QR-code. Then click on `Sign in`. Or simply click on the link.</h3>
</div>
<div>
	<img src="{{ qr64 }}" class="center" />
</div>
<div>
	<a href="{{ url_complete }}">{{ url_complete }}</a>
</div>

{% endblock content %}

mvw/accounts/templates/accounts/forgotten.html
{% extends 'base.html'%}

{% load crispy_forms_tags %}

{% load static %}

{% block imgheader %}
{% endblock imgheader %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
{% endblock content %}

mvw/accounts/templates/accounts/forgotten_password_done.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div class="row clearfix">
    <div class="span3 offset4">
        <h1 class="auth-lock-icon">{% trans "Forgotten Password" %}</h1>
        <p class="text-info">{% trans "If you have an account with us you will receive an email with instructions on how to reset your password." %}</p>
    </div>
</div>
{% endblock %}

mvw/accounts/templates/accounts/login.html
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<a href="{% url 'accounts:forgotten' %}"><span class="float-left">Forget your password?</span></a>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

mvw/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>New/Update User</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit">Save</button>
    </form>
{% endblock %}

mvw/accounts/templates/accounts/signup.html
{% extends 'core/base.html'%}

{% load crispy_forms_tags %}

{% load static %}

{% block imgheader %}
{% endblock imgheader %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
{% endblock content %}

mvw/accounts/templates/accounts/user-delete-confirm.html
{% extends 'core/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to remove "{{ user.username }}" ?</h2>
        <a href="{% url 'walk:home' %}">Cancel</a>
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

mvw/accounts/templates/accounts/user-form.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Profile</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit">Save</button>
    </form>

    <a href="{% url 'accounts:delete_user' %}">Delete</a>
{% endblock %}

mvw/accounts/templates/accounts/users.html
{% extends 'home.html' %}

{% block content %}
    <h2>Users list</h2>
    <ul>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">email</th>
                </tr>
            </thead>
            {% for user in users %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>
                        <a href="{% url 'accounts:update_user' user.id %}">
                            {{ user.email }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </ul>
{% endblock %}